### ISSUE TITLE
Create GitHub Action to Deploy site

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/unifiedjs.github.io#19]
### Subject of the feature

Use GitHub actions to help automate the release process, and potentially use web hooks to ensure updates happen when changes have been made.

### Problem

Currently deployment is done off local machines and is a manual process.
This leads to delays/lag in deploying changes, and puts the owness of regularly doing updates solely on the core team

### Expected behaviour

Have a GitHub action that can be run to deploy the site.

Optionally:
* Have a web hook to update the site when new commits are pushed to the master branch of the website repo
* Have a web hook to update the site when new OpenCollective supporters join.
* Have a schedule trigger (maybe daily or weekly) to regularly deploy/pick up changes from the Unified community

### Alternatives

* Continue to do manual deployment
* Use another CI provider to handle updates

**Comment by wooorm** [comment]
I’m all up for GH! But: Travis currently builds the site on every push, and in a cron job (every day), so much of this is already done; all the expected behaviour in your list should be done!

Still, the site takes a lot of time to build, and there are many ways to improve it (to explain, for me this was another experiment to see what a higher layer above unified would need), so I’m all ears!

**Comment by ChristianMurphy** [comment]
Whoops missed that Travis was setup for deployment, marking this as resolved
