### ISSUE TITLE
Add a new homepage, because Black Lives Matter

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/unifiedjs.github.io#32]
https://github.com/unifiedjs/unifiedjs.github.io/tree/blm

Related to https://github.com/mdx-js/mdx/pull/1094

(technically: I’ll probably switch the branches out)

**Comment by wooorm** [comment]
P.S. Website is already live because Travis, and it’s not a PR because it’s an entirely new branch.

**Comment by ChristianMurphy** [comment]
Might it make sense to include a similar snippet to what django-rest-framework did:

> The REST framework documentation remains accessible on the GitHub repo.

?

Or in this case

> The unified documentation remains accessible on the [GitHub repo](https://github.com/unifiedjs/unifiedjs.github.io/tree/backup).

**Comment by wooorm** [comment]
Good idea!

**Comment by wooorm** [comment]
Done!

**Comment by Murderlon** [comment]
Good to see unified taking a stand as well! Thanks.

**Comment by chmac** [comment]
Thanks for taking a stand on this.

Do you have a sense of how long the docs should be offline for?

I notice that many of the links from DuckDuckGo are broken. I think it's because the docs site was replaced by a single homepage. I notice the django site linked above has added a banner to the homepage, so it seems the original content is still online as well as the banner. I wonder if unified might be able to move towards this?

**Comment by wooorm** [comment]
Monday, probably: `https://github.com/nodejs/nodejs.org/pull/3246`.

**Comment by wooorm** [comment]
New bar is now live, docs are back up!
